name: Posting Normal
on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Variable setup
        env:
          ACCOUNT1: ${{ secrets.ACCOUNT_1_TOKEN }}
          ACCOUNT2: ${{ secrets.ACCOUNT_2_TOKEN }}
          ACCOUNT3: ${{ secrets.ACCOUNT_3_TOKEN }}
          ACCOUNT4: ${{ secrets.ACCOUNT_4_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
          ADS: ${{ vars.NORMAL_ADS }}
          URLS: ${{ vars.NORMAL_URLS }}
          AD_TYPE: Normal
        run: |
          python3 vv.py
        
