name: Posting Normal
on:
  schedule:
    - cron: '0 1-23/2 * * *' # Every 2 hours starting from 01:00
  workflow_dispatch:

jobs:
  post:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies (if needed)
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Run ad posting script
        env:
          ACCOUNT1: ${{ secrets.ACCOUNT_1_TOKEN }}
          ACCOUNT2: ${{ secrets.ACCOUNT_2_TOKEN }}
          ACCOUNT3: ${{ secrets.ACCOUNT_3_TOKEN }}
          ACCOUNT4: ${{ secrets.ACCOUNT_4_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NOTIONKEY: ${{ secrets.NOTIONKEY }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
          ADS: ${{ vars.NORMAL_ADS }}
          URLS: ${{ vars.NORMAL_URLS }}
          BASE_VARIABLE: ${{ vars.BASE_VARIABLE }}
          AD_TYPE: Normal
          DatabaseID: 2420bcea8f408017a788f21259365a1a
        run: |
          python3 vv.py

      - name: Commit Updated Tracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tracker.txt
          git commit -m "Update ad tracker"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
